import React, { useEffect, useMemo, useRef, useState } from "react";
import { AudioLines, CheckCircle2, ClipboardList, FileUp, Image as ImageIcon, Loader2, Mic, Square, Send, Sparkles, Type, X } from "lucide-react";
import { apiClient, type ResponsibleEntity, type SpeechTranscriptionResult } from "@/src/lib/apiClient";
import { cn } from "@/src/lib/utils";
import { useSyncedAppData } from "@/src/hooks/useSyncedAppData";
import { useProjectBoardData } from "@/src/hooks/useProjectBoardData";
import { formatLocalDate } from "@/src/lib/management";
import { browserSpeechPhrases, correctBrowserTranscript } from "@/src/lib/speechHotwords";
import { useUnifiedTasks } from "@/src/lib/taskModel";

type InputType = "text" | "image" | "audio";
type ProjectMatchType = "existing" | "new" | "unknown";
type AnalysisItem = { id: string; title: string; summary: string; projectId: string; projectName: string; projectMatchType?: ProjectMatchType; projectMatchConfidence?: number; assignee: string; assignees?: string[]; responsibleEntities?: ResponsibleEntity[]; deadline: string; dueTime?: string; confidence: number; needsManualReview: boolean; reviewReasons?: string[] };
type AnalysisResult = AnalysisItem & { transcript?: string; cleanedTranscript?: string; backgroundNotes?: string[]; skillVersion?: string; reviewPassApplied?: boolean; items: AnalysisItem[] };
type SpeechRecognitionLike = { continuous: boolean; interimResults: boolean; lang: string; onresult: ((event: any) => void) | null; onend: (() => void) | null; onerror: ((event: any) => void) | null; start: () => void; stop: () => void; abort: () => void };

const today = () => formatLocalDate();
const entityTypeLabel: Record<string, string> = { internal_person: "内部人员", partner_organization: "合作单位", supplier_organization: "供应商", external_person: "待登记人员", external_organization: "待登记单位" };
function readFileAsBase64(file: File) {
  return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => { const result = String(reader.result || ""); resolve(result.includes(",") ? result.split(",")[1] : result); }; reader.onerror = () => reject(reader.error); reader.readAsDataURL(file); });
}
function supportedAudioMimeType() {
  if (typeof MediaRecorder === "undefined" || typeof MediaRecorder.isTypeSupported !== "function") return "audio/webm";
  return ["audio/webm;codecs=opus", "audio/webm", "audio/mp4", "audio/ogg;codecs=opus", "audio/wav"].find((type) => MediaRecorder.isTypeSupported(type)) || "audio/webm";
}
function audioExtension(mimeType: string) {
  if (/mp4|m4a/i.test(mimeType)) return "m4a";
  if (/ogg/i.test(mimeType)) return "ogg";
  if (/wav/i.test(mimeType)) return "wav";
  return "webm";
}
function normalizeResult(result: any, fallbackText = ""): AnalysisResult {
  const sourceItems = Array.isArray(result?.items) && result.items.length ? result.items : [result];
  const items: AnalysisItem[] = sourceItems.filter(Boolean).map((item: any, index: number) => { const responsibleEntities = (Array.isArray(item?.responsibleEntities) ? item.responsibleEntities : []).filter((entity: ResponsibleEntity) => entity.entityType === "internal_person"); const assignees = Array.from(new Set([...(Array.isArray(item?.assignees) ? item.assignees : []), item?.assignee].filter(Boolean))); return { id: item?.id || `draft-${index + 1}`, title: String(item?.title || ""), summary: String(item?.summary || item?.title || fallbackText), projectId: String(item?.projectId || ""), projectName: String(item?.projectName || ""), projectMatchType: item?.projectMatchType || (item?.projectId ? "existing" : "unknown"), projectMatchConfidence: Number(item?.projectMatchConfidence || 0), assignee: String(responsibleEntities[0]?.name || assignees[0] || ""), assignees: responsibleEntities.length ? responsibleEntities.map((entity) => entity.name) : assignees, responsibleEntities, deadline: String(item?.deadline || ""), dueTime: String(item?.dueTime || ""), confidence: Number(item?.confidence || 0), needsManualReview: Boolean(item?.needsManualReview), reviewReasons: Array.isArray(item?.reviewReasons) ? item.reviewReasons.map(String) : [] }; });
  const first = items[0] || { id: "draft-1", title: "", summary: fallbackText, projectId: "", projectName: "", projectMatchType: "unknown" as const, projectMatchConfidence: 0, assignee: "", assignees: [], responsibleEntities: [], deadline: "", dueTime: "", confidence: 0, needsManualReview: true, reviewReasons: ["未识别出可执行任务"] };
  return { ...first, items, transcript: String(result?.transcript || fallbackText), cleanedTranscript: String(result?.cleanedTranscript || result?.transcript || fallbackText), backgroundNotes: Array.isArray(result?.backgroundNotes) ? result.backgroundNotes.map(String) : [], skillVersion: String(result?.skillVersion || ""), reviewPassApplied: Boolean(result?.reviewPassApplied) };
}

export function SmartIntake({ setActiveTab }: { setActiveTab: (tab: string) => void }) {
  const [isOpen, setIsOpen] = useState(false); const [inputType, setInputType] = useState<InputType>("audio"); const [rawText, setRawText] = useState(""); const [browserTranscript, setBrowserTranscript] = useState(""); const [transcription, setTranscription] = useState<SpeechTranscriptionResult | null>(null); const [cleanedText, setCleanedText] = useState(""); const [analysisStale, setAnalysisStale] = useState(false); const [companyEntities, setCompanyEntities] = useState<Array<ResponsibleEntity & { role?: string }>>([]); const [attachment, setAttachment] = useState<{ name: string; url?: string; audioId?: string; type: InputType } | null>(null); const [analysis, setAnalysis] = useState<AnalysisResult | null>(null); const [isAnalyzing, setIsAnalyzing] = useState(false); const [isSaving, setIsSaving] = useState(false); const [isRecording, setIsRecording] = useState(false); const [recordingSeconds, setRecordingSeconds] = useState(0); const [error, setError] = useState(""); const [transcriptionSource, setTranscriptionSource] = useState("");
  const recorderRef = useRef<MediaRecorder | null>(null); const recordingChunksRef = useRef<Blob[]>([]); const recordingTimerRef = useRef<number | null>(null); const recordingStartedAtRef = useRef(0); const speechRecognitionRef = useRef<SpeechRecognitionLike | null>(null); const speechRecognitionActiveRef = useRef(false); const browserTranscriptRef = useRef("");
  const [projectBoardData] = useProjectBoardData(); const [personnelData] = useSyncedAppData<any[]>("personnelData", []); const [quickIntakeItems, setQuickIntakeItems] = useSyncedAppData<any[]>("quickIntakeItems", []); const { tasks: workMemos, setTasks: setWorkMemos } = useUnifiedTasks();
  const allProjects = useMemo(() => Array.isArray(projectBoardData) ? projectBoardData.flatMap((col: any) => col.projects || []) : [], [projectBoardData]);
  const internalCompanyEntities = useMemo(() => companyEntities.filter((entity) => entity.entityType === "internal_person"), [companyEntities]);

  useEffect(() => { const legacyItems = Array.isArray(quickIntakeItems) ? quickIntakeItems : []; if (!legacyItems.length) return; const existingIds = new Set((Array.isArray(workMemos) ? workMemos : []).map((item: any) => item.id)); const migrated = legacyItems.filter((item: any) => !existingIds.has(item.id)).map((item: any) => ({ id: item.id, title: item.title || "未命名工作安排", detail: item.summary || "", projectId: item.projectId || "", projectName: item.projectName || "", assignee: item.assignee || "待指派", assignees: item.assignees || (item.assignee ? [item.assignee] : []), creator: item.createdBy || "系统用户", dueDate: item.deadline || today(), priority: "normal", status: item.status === "confirmed" ? "confirmed" : "pending", feedback: "", source: "quick-intake", sourceType: item.sourceType, attachmentUrl: item.attachmentUrl || "", createdAt: item.createdAt || new Date().toISOString() })); if (migrated.length) void setWorkMemos([...(Array.isArray(workMemos) ? workMemos : []), ...migrated]); void setQuickIntakeItems([]); }, [quickIntakeItems, workMemos, setQuickIntakeItems, setWorkMemos]);
  useEffect(() => { const open = () => { setIsOpen(true); void apiClient.getCompanyEntities().then((result) => setCompanyEntities(Array.isArray(result?.entities) ? result.entities : [])).catch(() => setCompanyEntities([])); }; window.addEventListener("open-smart-intake", open); return () => window.removeEventListener("open-smart-intake", open); }, []);
  useEffect(() => () => { if (recordingTimerRef.current) window.clearInterval(recordingTimerRef.current); speechRecognitionActiveRef.current = false; speechRecognitionRef.current?.abort(); recorderRef.current?.stream.getTracks().forEach((track) => track.stop()); }, []);

  const stopBrowserTranscription = () => { speechRecognitionActiveRef.current = false; try { speechRecognitionRef.current?.stop(); } catch { /* Recognition may already be stopped. */ } speechRecognitionRef.current = null; };
  const startBrowserTranscription = () => { const Recognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition; if (!Recognition) return false; const recognition: SpeechRecognitionLike = new Recognition(); recognition.continuous = true; recognition.interimResults = true; recognition.lang = "zh-CN"; const phrases = browserSpeechPhrases(allProjects, internalCompanyEntities); if (phrases.length && "phrases" in recognition) { try { (recognition as any).phrases = phrases.map((phrase) => ({ phrase, boost: 8 })); } catch { /* Browser may not implement SpeechRecognitionPhrase. */ } } recognition.onresult = (event: any) => { let finalText = ""; let interimText = ""; for (let index = 0; index < event.results.length; index += 1) { const text = String(event.results[index]?.[0]?.transcript || ""); if (event.results[index].isFinal) finalText += text; else interimText += text; } const latest = correctBrowserTranscript(`${finalText}${interimText}`.trim(), allProjects, internalCompanyEntities); browserTranscriptRef.current = latest; setBrowserTranscript(latest); }; recognition.onerror = (event: any) => { if (event?.error !== "no-speech") speechRecognitionActiveRef.current = false; }; recognition.onend = () => { if (!speechRecognitionActiveRef.current) return; window.setTimeout(() => { if (!speechRecognitionActiveRef.current) return; try { recognition.start(); } catch { /* Browser will retry on the next recording. */ } }, 200); }; try { speechRecognitionActiveRef.current = true; recognition.start(); speechRecognitionRef.current = recognition; return true; } catch { speechRecognitionActiveRef.current = false; return false; } };
  const releaseAudio = async (audioId = attachment?.audioId) => { if (!audioId) return; try { await apiClient.deleteIntakeAudio(audioId); } catch { /* Audio may already have been deleted. */ } };
  const reset = () => { if (recordingTimerRef.current) window.clearInterval(recordingTimerRef.current); stopBrowserTranscription(); recorderRef.current?.stream.getTracks().forEach((track) => track.stop()); recorderRef.current = null; browserTranscriptRef.current = ""; setInputType("audio"); setRawText(""); setBrowserTranscript(""); setTranscription(null); setCleanedText(""); setAnalysisStale(false); setAttachment(null); setAnalysis(null); setIsAnalyzing(false); setIsSaving(false); setIsRecording(false); setRecordingSeconds(0); setError(""); setTranscriptionSource(""); };
  const close = () => { const audioId = attachment?.audioId; setIsOpen(false); reset(); void releaseAudio(audioId); };
  const analyzeUploaded = async (file: File, type: InputType, previewTranscript = "", durationMs = 0) => { setError(""); setAnalysis(null); setIsAnalyzing(true); let uploadCompleted = false; try { const contentBase64 = await readFileAsBase64(file); if (type === "audio") { const uploaded = await apiClient.uploadIntakeAudio(file.name, contentBase64, file.type || "audio/webm", durationMs); uploadCompleted = true; setAttachment({ name: uploaded.filename, audioId: uploaded.audioId, type }); setBrowserTranscript(previewTranscript.trim()); const result = await apiClient.transcribeAudio(uploaded.audioId, previewTranscript.trim()); setTranscription(result); setRawText(result.correctedTranscript || result.rawTranscript || ""); setTranscriptionSource(result.model === "browser-fallback" ? "浏览器临时识别（正式引擎失败）" : result.provider === "doubao" ? `豆包 · ${result.model}` : `FunASR · ${result.model}`); if (result.warning) setError(result.warning); return; } const uploaded = await apiClient.uploadFile(file.name, contentBase64); uploadCompleted = true; setAttachment({ name: uploaded.filename, url: uploaded.url, type }); const result = await apiClient.analyzeIntake({ inputType: type, attachmentUrl: uploaded.url, projects: allProjects, personnel: personnelData }); setAnalysis(normalizeResult({ ...result, title: result.title === "根据附件补充待办事项" ? "" : result.title }, rawText)); } catch (caughtError: any) { const providerMessage = String(caughtError?.details?.message || caughtError?.message || ""); if (type === "audio" && uploadCompleted) { if (previewTranscript.trim()) { setRawText(previewTranscript.trim()); setTranscriptionSource("浏览器临时识别（正式引擎失败）"); } else setTranscriptionSource(""); setError(`正式语音识别服务不可用${providerMessage ? `：${providerMessage}` : ""}。${previewTranscript.trim() ? "当前保留浏览器临时字幕，请人工核对后继续。" : "请检查后台 ASR/FunASR 服务，或改用文字录入。"}`); } else { setError(`录音上传失败${providerMessage ? `：${providerMessage}` : ""}，请确认后台服务和网络正常后重试。`); } } finally { setIsAnalyzing(false); } };
  const handleFileChange = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) await analyzeUploaded(file, inputType); event.target.value = ""; };
  const startRecording = async () => { try { if (!navigator.mediaDevices?.getUserMedia || typeof MediaRecorder === "undefined") throw new Error("当前浏览器不支持录音"); await releaseAudio(); const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const mimeType = supportedAudioMimeType(); const recorder = new MediaRecorder(stream, mimeType ? { mimeType } : undefined); recordingChunksRef.current = []; recordingStartedAtRef.current = Date.now(); browserTranscriptRef.current = ""; setRawText(""); setBrowserTranscript(""); setTranscription(null); setAttachment(null); setTranscriptionSource(""); setError(""); startBrowserTranscription(); recorder.ondataavailable = (event) => { if (event.data.size) recordingChunksRef.current.push(event.data); }; recorder.onstop = async () => { recorder.stream.getTracks().forEach((track) => track.stop()); await new Promise((resolve) => window.setTimeout(resolve, 250)); const blob = new Blob(recordingChunksRef.current, { type: recorder.mimeType || mimeType || "audio/webm" }); const extension = audioExtension(blob.type || mimeType); await analyzeUploaded(new File([blob], `语音任务-${Date.now()}.${extension}`, { type: blob.type || mimeType }), "audio", browserTranscriptRef.current, Date.now() - recordingStartedAtRef.current); }; recorder.start(); recorderRef.current = recorder; setIsRecording(true); setRecordingSeconds(0); recordingTimerRef.current = window.setInterval(() => setRecordingSeconds((seconds) => seconds + 1), 1000); } catch (caughtError: any) { stopBrowserTranscription(); setError(`无法开始录音：${String(caughtError?.message || "请检查浏览器麦克风权限")}`); } };
  const stopRecording = () => { if (recordingTimerRef.current) window.clearInterval(recordingTimerRef.current); stopBrowserTranscription(); recorderRef.current?.stop(); setIsRecording(false); };
  const selectInputType = (nextType: InputType) => { if (nextType !== "audio" && attachment?.audioId) void releaseAudio(attachment.audioId); setInputType(nextType); setAttachment(null); setTranscription(null); setBrowserTranscript(""); setRawText(""); setAnalysis(null); setError(""); };
  const analyzeText = async (textOverride?: string) => { const source = String(textOverride ?? rawText).trim(); if (!source) { setError("请先输入一段待办内容。"); return; } setError(""); setIsAnalyzing(true); try { const result = await apiClient.analyzeIntake({ inputType: "text", text: source, projects: allProjects, personnel: personnelData }); const normalized = normalizeResult(result, source); setAnalysis(normalized); setCleanedText(normalized.cleanedTranscript || source); setAnalysisStale(false); } catch { setAnalysis(normalizeResult({ transcript: source, cleanedTranscript: source, backgroundNotes: [], skillVersion: "client-fallback-v1", items: [{ title: "", summary: source, projectId: "", projectName: "", projectMatchType: "unknown", responsibleEntities: [], assignees: [], assignee: "", deadline: "", confidence: 0.1, needsManualReview: true, reviewReasons: ["服务暂不可用，请人工补充任务信息"] }] }, source)); setCleanedText(source); setAnalysisStale(false); } finally { setIsAnalyzing(false); } };
  const updateItem = (index: number, patch: Partial<AnalysisItem>) => setAnalysis((current) => { if (!current) return current; const items = current.items.map((item, itemIndex) => { if (itemIndex !== index) return item; const next = { ...item, ...patch }; const names = next.responsibleEntities?.filter((entity) => entity.matchType !== "ambiguous").map((entity) => entity.name) || next.assignees || []; return { ...next, assignees: names, assignee: names[0] || patch.assignee || "" }; }); return { ...current, ...items[0], items }; });
  const addResponsible = (index: number, entity: ResponsibleEntity) => { if (entity.entityType !== "internal_person") return; const current = analysis?.items[index]?.responsibleEntities?.filter((item) => item.entityType === "internal_person") || []; if (current.some((item) => item.entityId === entity.entityId)) return; updateItem(index, { responsibleEntities: [...current, entity] }); };
  const removeResponsible = (index: number, entityId: string) => updateItem(index, { responsibleEntities: (analysis?.items[index]?.responsibleEntities || []).filter((entity) => entity.entityId !== entityId && entity.entityType === "internal_person") });
  const removeItem = (index: number) => setAnalysis((current) => current ? { ...current, items: current.items.filter((_, itemIndex) => itemIndex !== index) } : current);
  const confirmTasks = async () => {
    if (analysisStale) { setError("AI整理稿已修改，请先重新生成任务。"); return; }
    if (!analysis?.items.length) { setError("请至少保留一条任务。"); return; }
    if (analysis.items.some((item) => !item.title.trim() || !item.deadline || !(item.responsibleEntities?.filter((entity) => entity.entityType === "internal_person" && entity.matchType !== "ambiguous").length || item.assignees?.some((name) => internalCompanyEntities.some((entity) => entity.name === name)) || (item.assignee && internalCompanyEntities.some((entity) => entity.name === item.assignee))))) {
      setError("请为每条任务补充标题、内部负责人和日期，并处理多候选项。"); return;
    }
    setIsSaving(true); setError("");
    const now = new Date().toISOString();
    const newMemos = analysis.items.map((item) => {
      const id = `task-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
      const responsibleEntities = (item.responsibleEntities || []).filter((entity) => entity.entityType === "internal_person");
      const assignees = responsibleEntities.length ? responsibleEntities.filter((entity) => entity.matchType !== "ambiguous").map((entity) => entity.name) : (item.assignees?.length ? item.assignees : [item.assignee]).filter((name) => internalCompanyEntities.some((entity) => entity.name === name));
      return { id, title: item.title.trim(), name: item.title.trim(), detail: item.summary || analysis.cleanedTranscript || analysis.transcript || attachment?.name || rawText, projectId: item.projectId, projectName: item.projectName, projectMatchType: item.projectMatchType || "unknown", responsibleEntities, assignee: assignees[0], assignees, creator: "快速创建", createdBy: "快速创建", dueDate: item.deadline, deadline: item.deadline, dueTime: item.dueTime || "", priority: "normal", status: "pending", feedback: "", source: "quick-intake", sourceType: inputType, transcript: analysis.transcript || rawText, cleanedTranscript: analysis.cleanedTranscript || cleanedText, backgroundNotes: analysis.backgroundNotes || [], skillVersion: analysis.skillVersion || "", attachmentUrl: attachment?.url || "", createdAt: now, updatedAt: now };
    });
    await setWorkMemos((current) => [...newMemos, ...(Array.isArray(current) ? current : [])]);
    await releaseAudio(); setIsSaving(false);
    window.dispatchEvent(new CustomEvent("show-toast", { detail: `${newMemos.length} 条任务已加入统一任务中心` }));
    setAttachment(null); close(); setActiveTab("work-memo");
  };
  const formatSeconds = (seconds: number) => `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`;

  return <>{isOpen && <div className="fixed inset-0 z-50 bg-slate-900/50 backdrop-blur-sm flex items-end justify-center p-0 md:items-center md:p-4">
<div className="w-full max-w-4xl bg-white rounded-t-2xl shadow-xl max-h-[94dvh] flex flex-col overflow-hidden md:rounded-2xl md:max-h-[92vh]">
<div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between">
<div>
<h3 className="text-xl font-bold text-slate-900 flex items-center gap-2">
<Sparkles className="w-5 h-5 text-indigo-600" />快速创建工作备忘</h3>
<p className="text-sm text-slate-500 mt-1">直接说项目、事项、负责人和时间，AI 会生成待确认任务清单。</p>
</div>
<button onClick={close} className="p-2 rounded-lg text-slate-400 hover:bg-slate-100">
<X className="w-5 h-5" />
</button>
</div>
<div className="p-6 overflow-y-auto space-y-6">
<div className="rounded-2xl border border-indigo-100 bg-indigo-50/60 p-3"><div className="mb-2 flex items-center gap-2 px-1 text-xs font-bold uppercase tracking-wide text-indigo-700"><AudioLines className="h-4 w-4" />优先使用语音快速记录</div><div className="grid grid-cols-3 gap-2 bg-white/70 p-1 rounded-xl">{([{ id: "audio", label: "语音", icon: Mic }, { id: "text", label: "文字", icon: Type }, { id: "image", label: "截图", icon: ImageIcon }] as const).map(({ id, label, icon: Icon }) => <button key={id} onClick={() => selectInputType(id)} className={cn("flex items-center justify-center gap-2 rounded-lg py-2.5 text-sm font-bold", inputType === id ? "bg-white text-indigo-600 shadow-sm" : "text-slate-600")}>
<Icon className="w-4 h-4" />{label}</button>)}</div></div>{inputType === "text" && <div className="space-y-3">
<textarea value={rawText} onChange={(event) => { setRawText(event.target.value); setAnalysis(null); }} placeholder="例如：明天 A 区项目让王强和李娜检查设备，下午三点前完成" className="w-full min-h-32 resize-none rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-indigo-500" />
<button onClick={() => void analyzeText()} disabled={isAnalyzing} className="inline-flex items-center gap-2 rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{isAnalyzing ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}生成预览</button>
</div>}{inputType !== "text" && <div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-6 text-center">
<div className="mx-auto mb-3 w-12 h-12 rounded-full bg-white flex items-center justify-center text-indigo-600 shadow-sm">{inputType === "image" ? <ImageIcon className="w-6 h-6" /> : <AudioLines className="w-6 h-6" />}</div>{inputType === "audio" ? <>
<p className="text-base font-bold text-slate-900">{isRecording ? `正在录音 ${formatSeconds(recordingSeconds)}` : "说出项目、事项、负责人和截止时间"}</p><p className="mt-1 text-xs text-slate-500">录音结束后会自动转写，再交给 DeepSeek 整理成待确认任务。</p>
<button type="button" onClick={isRecording ? stopRecording : startRecording} disabled={isAnalyzing} className={cn("mx-auto mt-5 flex min-h-20 w-full max-w-sm items-center justify-center gap-3 rounded-2xl px-6 py-5 text-lg font-bold text-white shadow-lg transition hover:scale-[1.01] disabled:cursor-not-allowed disabled:opacity-60", isRecording ? "bg-rose-600 shadow-rose-200" : "bg-indigo-600 shadow-indigo-200")}>{isRecording ? <>
<Square className="w-4 h-4" />停止录音</> : <>
<Mic className="w-4 h-4" />开始录音</>}</button>{isRecording && <div className="mx-auto mt-4 flex items-center justify-center gap-2 text-xs font-bold text-rose-600"><span className="h-2.5 w-2.5 animate-pulse rounded-full bg-rose-500" />正在监听，请清晰说话</div>}{isRecording && browserTranscript.trim() && <p className="mx-auto mt-4 max-w-xl rounded-lg bg-white px-3 py-2 text-left text-sm text-slate-700 shadow-sm">浏览器临时字幕（仅供参考）：{browserTranscript}</p>}</> : <>
<p className="text-sm font-medium text-slate-900">上传聊天截图</p>
<label className="mt-4 inline-flex cursor-pointer items-center gap-2 rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white">
<FileUp className="w-4 h-4" />选择文件<input type="file" className="hidden" accept="image/*" onChange={handleFileChange} />
</label>
</>}{attachment && <p className="text-xs text-slate-500 mt-3">已安全保存：{attachment.name}</p>}{isAnalyzing && <p className="mt-3 text-xs text-indigo-600">正在调用 FunASR 正式转写并加载公司热词…</p>}</div>}{inputType === "audio" && attachment && <div className="rounded-xl border border-indigo-200 bg-indigo-50/50 p-4 space-y-3">
<div className="flex items-center justify-between gap-3">
<span className="text-sm font-bold text-slate-900">服务端正式转写</span>
<span className="text-xs text-slate-500">{transcriptionSource || "等待 FunASR 返回"}</span>
</div>
{browserTranscript && <details className="rounded-lg bg-white px-3 py-2 text-xs text-slate-600"><summary className="cursor-pointer font-medium">浏览器临时字幕（仅供参考）</summary><p className="mt-2 whitespace-pre-wrap">{browserTranscript}</p></details>}
{transcription?.rawTranscript && transcription.rawTranscript !== transcription.correctedTranscript && <details className="rounded-lg bg-white px-3 py-2 text-xs text-slate-600"><summary className="cursor-pointer font-medium">FunASR 原始结果</summary><p className="mt-2 whitespace-pre-wrap">{transcription.rawTranscript}</p></details>}
{transcription && <div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-white px-2.5 py-1 text-slate-600">模型：{transcription.model}</span><span className="rounded-full bg-white px-2.5 py-1 text-slate-600">耗时：{transcription.processingMs}ms</span><span className="rounded-full bg-white px-2.5 py-1 text-slate-600">热词：{transcription.hotwordsApplied ? `${transcription.hotwordCount} 个` : "未使用"}</span>{transcription.fallbackApplied && <span className="rounded-full bg-amber-100 px-2.5 py-1 text-amber-800">已启用降级</span>}</div>}
{Boolean(transcription?.corrections.length) && <div className="rounded-lg bg-emerald-50 px-3 py-2 text-xs text-emerald-800"><span className="font-bold">公司专名校正：</span>{transcription!.corrections.map((item) => `${item.original} → ${item.replacement}`).join("；")}</div>}
{Boolean(transcription?.ambiguousCorrections.length) && <div className="rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-800"><span className="font-bold">存在多候选：</span>{transcription!.ambiguousCorrections.map((item) => `${item.original}（${item.candidates.map((candidate) => candidate.name).join(" / ")}）`).join("；")}，请在任务卡中人工选择。</div>}
<textarea value={rawText} onChange={(event) => { setRawText(event.target.value); setAnalysis(null); }} placeholder="正式转写会显示在这里，也可以手动修正" className="w-full min-h-28 resize-none rounded-lg border border-indigo-100 bg-white px-3 py-2 text-sm outline-none focus:border-indigo-500" />{rawText.trim() && <button onClick={() => void analyzeText()} disabled={isAnalyzing} className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{isAnalyzing ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}交给 DeepSeek 生成任务清单</button>}</div>}{error && <div className="rounded-lg bg-rose-50 border border-rose-100 px-4 py-3 text-sm text-rose-600">{error}</div>}{analysis && <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm space-y-4">
<details className="rounded-lg bg-slate-50 px-4 py-3 text-sm text-slate-600"><summary className="cursor-pointer font-medium text-slate-700">原始转写</summary><p className="mt-2 whitespace-pre-wrap">{analysis.transcript || rawText || "附件内容"}</p></details>
<div className="space-y-2"><div className="flex items-center justify-between"><label className="text-sm font-bold text-slate-900">AI 整理稿</label>{analysis.reviewPassApplied && <span className="text-xs text-indigo-600">已自动复核</span>}</div><textarea value={cleanedText} onChange={(event) => { setCleanedText(event.target.value); setAnalysisStale(true); }} rows={4} className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" />{analysisStale && <div className="flex items-center justify-between rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-700"><span>整理稿已修改，现有任务已失效。</span><button onClick={() => void analyzeText(cleanedText)} className="font-bold text-indigo-600">重新生成任务</button></div>}</div>
{Boolean(analysis.backgroundNotes?.length) && <div className="rounded-lg bg-emerald-50 px-4 py-3"><p className="text-sm font-bold text-emerald-800">背景／已完成信息</p><ul className="mt-1 list-disc pl-5 text-sm text-emerald-700">{analysis.backgroundNotes!.map((note, index) => <li key={`${note}-${index}`}>{note}</li>)}</ul></div>}
<div className="flex items-center justify-between">
<h4 className="font-bold text-slate-900 flex items-center gap-2">
<CheckCircle2 className="w-5 h-5 text-emerald-500" />待确认任务清单（{analysis.items.length}）</h4>
<span className="text-xs text-slate-500">规则版本：{analysis.skillVersion || "兼容模式"}</span>
</div>{analysis.items.map((item, index) => { const projectValue = item.projectId || item.projectName; return <div key={item.id} className="rounded-xl border border-slate-200 p-4 space-y-3">
<div className="flex items-center justify-between">
<span className="text-xs font-bold text-indigo-600">任务 {index + 1}</span>
<button type="button" onClick={() => removeItem(index)} className="text-xs text-rose-500 hover:text-rose-700">删除</button>
</div>
<input value={item.title} onChange={(event) => updateItem(index, { title: event.target.value })} className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm font-medium" placeholder="任务标题" />
<textarea value={item.summary} onChange={(event) => updateItem(index, { summary: event.target.value })} className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" rows={2} placeholder="任务说明" />
<div className="grid grid-cols-1 md:grid-cols-3 gap-3">
<label className="text-xs text-slate-500"><span className="flex items-center justify-between">项目<span className={cn("rounded-full px-2 py-0.5 text-[10px] font-bold", item.projectMatchType === "existing" ? "bg-emerald-50 text-emerald-700" : item.projectMatchType === "new" ? "bg-amber-50 text-amber-700" : "bg-slate-100 text-slate-600")}>{item.projectMatchType === "existing" ? "已匹配已有项目" : item.projectMatchType === "new" ? "识别为新项目" : "待确认项目"}</span></span><select value={projectValue} onChange={(event) => { const project = allProjects.find((candidate: any) => candidate.id === event.target.value || candidate.name === event.target.value); updateItem(index, { projectId: project?.id || "", projectName: project?.name || event.target.value, projectMatchType: project ? "existing" : event.target.value ? "new" : "unknown", projectMatchConfidence: project ? 1 : 0.4 }); }} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-800">
<option value="">未关联项目</option>{allProjects.map((project: any) => <option key={project.id || project.name} value={project.id || project.name}>已有项目：{project.name}</option>)}{item.projectName && !item.projectId && <option value={item.projectName}>新项目：{item.projectName}</option>}</select>
</label>
<label className="text-xs text-slate-500">添加责任人<select value="" onChange={(event) => { const entity = internalCompanyEntities.find((candidate) => candidate.entityId === event.target.value); if (entity) addResponsible(index, entity); }} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-800"><option value="">{item.responsibleEntities?.length ? `已选择：${item.responsibleEntities.map((entity) => entity.name).join("、")}（可继续添加）` : "选择公司内部人员"}</option>{internalCompanyEntities.map((entity) => <option key={entity.entityId} value={entity.entityId}>内部人员：{entity.name}</option>)}</select>
</label>
<label className="text-xs text-slate-500">截止日期<input type="date" value={item.deadline} onChange={(event) => updateItem(index, { deadline: event.target.value })} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-800" />
</label>
</div><div className="flex flex-wrap gap-2">{(item.responsibleEntities || []).map((entity) => <span key={`${entity.entityId}-${entity.matchType}`} className={cn("inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs", entity.matchType === "ambiguous" ? "bg-amber-100 text-amber-800" : entity.matchType === "pending" ? "bg-slate-200 text-slate-700" : "bg-indigo-50 text-indigo-700")}>{entityTypeLabel[entity.entityType] || "责任主体"}：{entity.name}{entity.contactName ? `＋${entity.contactName}` : ""}<button type="button" onClick={() => removeResponsible(index, entity.entityId)} aria-label={`移除${entity.name}`}>×</button></span>)}</div>{item.responsibleEntities?.some((entity) => entity.matchType === "pending" || !entity.notificationEligible) && <p className="text-xs text-slate-600 rounded-lg bg-slate-50 px-3 py-2">待登记对象或无账号联系人可以保存，但不参与个人自动通知。</p>}{item.projectMatchType === "new" && <p className="text-xs text-amber-700 rounded-lg bg-amber-50 px-3 py-2">AI 识别为新项目，当前仅保存项目草稿，不会自动创建项目。</p>}{item.needsManualReview && <p className="text-xs text-amber-700 rounded-lg bg-amber-50 px-3 py-2">{item.reviewReasons?.length ? item.reviewReasons.join("；") : "该任务需要人工核对识别结果。"}</p>}</div>; })}
<div className="flex justify-end gap-3 pt-2">
<button onClick={() => setAnalysis(null)} className="px-4 py-2 text-sm text-slate-600">重新采集</button>
<button onClick={confirmTasks} disabled={isSaving || analysisStale} className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{isSaving ? <Loader2 className="w-4 h-4 animate-spin" /> : <ClipboardList className="w-4 h-4" />}确认并加入工作备忘</button>
</div>
</div>}</div>
</div>
</div>}</>;
}
